#!/bin/sh
PROG_NAME=$(basename $0)
MSG_PREFIX="$PROG_NAME[$(basename "$(pwd)")]"
INTERNAL_IN=.kianidraw/in
EXTERNAL_IN=in

path_to_root() {
	echo $1 | sed 's/[^/]\{1,\}/../g'
}

exit_bad_location() {
	echo "$PROG_NAME: not in a valid/usable kianidraw project" >&2
	exit 1
}

for flag in d r w x; do
	test -$flag $INTERNAL_IN || exit_bad_location
	test -$flag $EXTERNAL_IN || exit_bad_location
done

move=false
test X"$1" = X"-m" && {
	move=true
	shift
}

test $# -ge 2 && test $(expr $# % 2) -eq 0 || {
	echo "$MSG_PREFIX: at least 2 args required per imported resource: (<file> <resourceName>)..." >&2
	exit 64
}

while test $# -gt 0; do
	test -r "$1" || {
		echo "$MSG_PREFIX: warning: \"$1\" is not a readable file => skipped" >&2
		shift 2
		continue
	}

	sum=$(cksum "$1" | awk '{print $1}')
	! $(ls -A $EXTERNAL_IN | grep -q $sum) || {
		echo "$MSG_PREFIX: warning: \"$1\" already imported => skipped" >&2
		shift 2
		continue
	}

	test X$(expr "$2" : "\([_a-zA-Z0-9][-_.a-zA-Z0-9]*\)") = X"$2" >/dev/null || {
		echo "$MSG_PREFIX: warning: bad resource name: \"$2\" => skipped" >&2
		shift 2
		continue
	}

	test $2 != all || {
		echo "$MSG_PREFIX: warning: cannot name resource \"all\" (reserved keyword) => skipped" >&2
		shift 2
		continue
	}

	! test -f $INTERNAL_IN/$2 || {
		echo "$MSG_PREFIX: warning: resource name \"$2\" already in use => skipped" >&2
		shift 2
		continue
	}

	new_filename=${sum}_$(basename $1)

	if $move; then
		mv "$1" $EXTERNAL_IN/"$new_filename"
	else
		cp "$1" $EXTERNAL_IN/"$new_filename"
	fi
	ln -s $(path_to_root $INTERNAL_IN)/$EXTERNAL_IN/"$new_filename" $INTERNAL_IN/$2
	convert $INTERNAL_IN/$2 $INTERNAL_IN/$2.xcf

	sleep 1
	echo "$MSG_PREFIX: imported \"$1\" as \"$2\""
	shift 2
done
