#!/bin/sh
PROG_NAME=$(basename $0)
MSG_PREFIX=$PROG_NAME

test -n "$1" || {
	echo "$PROG_NAME: 1 arg required: <projectName>" >&2
	exit 64
}

mkdir "$1" 2>/dev/null || {
	echo "$MSG_PREFIX: cannot create project \"$1\" here" >&2
	exit 1
}

cd "$1"
mkdir -p .kianidraw/in in && echo "$MSG_PREFIX: created project \"$1\""
