#!/bin/sh
PROG_NAME=$(basename $0)
MSG_PREFIX="$PROG_NAME[$(basename "$(pwd)")]"
INTERNAL_IN=.kianidraw/in

exit_bad_location() {
	echo "$PROG_NAME: not in a valid/usable kianidraw project" >&2
	exit 1
}

for flag in d r w x; do
	test -$flag $INTERNAL_IN || exit_bad_location
done

test -n "$1" || {
	echo "$MSG_PREFIX: at least 1 arg required: all|(<resourceName>)..." >&2
	exit 64
}

cd $INTERNAL_IN

to_update=""
for arg; do
	if test X"$arg" = Xall; then
		to_update="$to_update $(find . -maxdepth 1 -type l | sed 's/^\.\///')"
	else
		test -L "$arg" || {
			echo "$MSG_PREFIX: warning: resource \"$arg\" not found" >&2
			continue
		}
		to_update="$to_update $arg"
	fi
done

for u in $to_update; do
	echo $u
done | uniq | while read resource; do
	test -f $resource.xcf || convert $resource $resource.xcf
done
