#!/bin/sh
PROG_NAME=$(basename $0)
INTERNAL_CONFIG=.kianidraw/config
INTERNAL_IN=.kianidraw/in
EXTERNAL_IN=in

test -n "$1" || {
	echo "$PROG_NAME: 1 arg required: <projectName>" >&2
	exit 64
}

mkdir "$1" 2>/dev/null || {
	echo "$PROG_NAME: \"$1\": cannot create this project here, please check permissions" >&2
	exit 1
}

cd "$1"
mkdir -p $INTERNAL_IN $EXTERNAL_IN \
&& { cat <<END
working_size_max=1920x1080
output_size_max=1280x720
duration=5
END
} > $INTERNAL_CONFIG \
&& echo "$PROG_NAME: created project \"$1\""
